title: Calidad de Software — Desarrollo de Software
description: Curso práctico de Ciencia de la Computación centrado en calidad de software y desarrollo a escala industrial con excelentes prácticas, con GitHub como columna vertebral del flujo de trabajo
baseurl: "/SoftwareQuality"
url: "https://ecuadros.github.io"
theme: null
markdown: kramdown
